sudo: false
language: node_js
node_js:
  - '5'

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
      - libc6-dev

cache:
  directories:
    - node_modules

env:
  global:
    - CC: /usr/bin/gcc-4.8
    - CXX: /usr/bin/g++-4.8
    - DISPLAY: ":99.0"
    - CHROME_URL=https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64
    - CHROME_REV=$(curl -s ${CHROME_URL}/LAST_CHANGE)
    - CHROME_CANARY_BIN=$PWD/browser/chrome-linux/chrome

before_install:
  - $CXX --version
  - npm install --global npm
  - npm --version
  - npm install --global gulp-cli
  - gulp --version

install:
  - npm install
  - cp build/ci/reporter.js node_modules/karma/lib/reporter.js
  - du -sh node_modules || true

before_script:
  - curl ${CHROME_URL}/${CHROME_REV}/chrome-linux.zip --create-dirs -o browser/chrome-linux.zip
  - unzip browser/chrome-linux.zip -d browser
  - sh -e /etc/init.d/xvfb start
  - sleep 5

script:
  - gulp ci

after_success:
  - npm run coveralls
